# Generated by Django 3.2 on 2022-10-09 08:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vps',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество ядер')),
                ('ram', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='объём RAM')),
                ('hdd', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='объём HDD')),
                ('status', models.CharField(choices=[('started', 'Запущен'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], max_length=20, verbose_name='Статус сервера')),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
                'db_table': 'vps',
            },
        ),
    ]
